default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Noboru.xcodeproj")
    build_app(scheme: "Noboru")
    upload_to_testflight
  end
end
