default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: ENV['XCODE_PROJECT'])
    build_app(scheme: ENV['XCODE_SCHEME'])
    upload_to_testflight(
      api_key: get_api_key,
      skip_waiting_for_build_processing: true
    )
    git_commit(path: "*", message: "Version Bump")
    add_version_tag
    push_to_git_remote(tags: true)
  end

  private_lane :get_api_key do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_KEY_ISSUER_ID'],
      key_content: ENV['APP_STOPRE_KEY_CONTENT'],
      in_house: false
    )
  end

  desc "Creates a tag with current project version and build number."
  private_lane :add_version_tag do
    version = get_version_number(xcodeproj: ENV['XCODE_PROJECT'], target: ENV['XCODE_SCHEME'])
    build = get_build_number(xcodeproj: ENV['XCODE_PROJECT'])
    add_git_tag(
      tag: "#{version}(#{build})"
    )
  end
end
